Added file tests
cryptic-game/integration-tests pull request #15
Opened 2020-09-01 17:54 UTC by T2brozz

**Description**
> Added test for device/hardware endpoint

**Issue**
Closes #1

2020-09-01 18:13 UTC, JannikEmmerich commented
@T2brozz Bitte statt 
> Added test for device/hardware endpoint

Added test for device/hardware endpoint

also ohne das > davor. 

Ich hab das mal geändert, aber für die Zukunft ;)

2020-09-01 18:14 UTC, JannikEmmerich requested changes
Please rebase the `issue/1-file-tests` branch onto `master`, instead of merging `master` into `issue/1-file-tests`!

Also rename the following commit:
```diff
- Added file tests(#1)
+ Added file tests (#1)
```

2020-10-03 23:50 UTC, Defelo approved these changes

2020-10-03 23:52 UTC, JannikEmmerich approved these changes

2020-10-03 23:52 UTC, merged