Added network tests
cryptic-game/integration-tests pull request #20
Opened 2020-10-13 08:36 UTC by T2brozz

**Description**
> added network tests 

**Issue**
Closes #9

2020-10-13 18:27 UTC, MarcelCoding requested changes
Please Squash 77945da22134427f750d60e0c6df8aca330e5a87 and 9e83b8b734534092f1158f47cdf32d8dcce6e632 or rename one of them.

2020-10-13 22:18 UTC, Defelo approved these changes

2020-10-14 09:56 UTC, JannikEmmerich approved these changes

2020-10-14 10:26 UTC, MarcelCoding approved these changes

2020-10-14 11:51 UTC, merged