Added service tests
cryptic-game/integration-tests pull request #24
Opened 2020-10-18 19:27 UTC by T2brozz

**Description**
Added tests for service endpoints.

**Issue**
Closes #4

2020-10-18 20:57 UTC, Defelo requested changes

2020-10-18 20:57 UTC, Defelo commented on tests/test_service.py
> +        actual = self.client.ms("service", ["public_info"], device_uuid=device_uuid, service_uuid=service_uuid)
Please leave an empty line between setup and assertions to improve readability. (applies to other test cases as well)

2020-10-18 20:57 UTC, Defelo commented on tests/test_service.py
> +            + "VALUES (%s,%s,%s,%s,%s,%s,%s)",
```suggestion
            "INSERT INTO service_service (uuid, device, owner, name, running, running_port, part_owner) "
            "VALUES (%s,%s,%s,%s,%s,%s,%s)",
```

2020-10-18 20:57 UTC, Defelo commented on tests/test_service.py
> +def create_service(device=uuid(), name="telnet", n=1, part_owner=None, owner=super_uuid, clear_service=True):
Don't call other functions in function definitions. As this is a required argument, remove the default value instead.

2020-10-18 20:57 UTC, Defelo commented on tests/test_service.py
> +        self.assertEqual(actual["device"], device_uuid)
The first parameter of the `assertEqual` function should be the expected value and the second one the actual value. (applies to other test cases as well)

2020-10-18 20:57 UTC, Defelo commented on tests/test_service.py
> +        self.assertEqual(actual["name"], "telnet")
Please define an `expected` variable and use `self.assertEqual(expected, actual)` instead. (applies to other test cases as well)

2020-10-21 11:25 UTC, Defelo approved these changes

2020-10-21 11:56 UTC, MarcelCoding approved these changes
Maby Merge 78a28e869d988da764ec0b00028753e205a455b6 and 44e49d833d0e5a9c72257d42ddb43ed519b4fd04

2020-10-21 12:30 UTC, merged